/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as DevPreviewRouteImport } from './routes/dev/preview'
import { Route as GithubInstallRouteImport } from './routes/github/install'
import { Route as GithubInstalledRouteImport } from './routes/github/installed'
import { Route as OwnerRepoSplatRouteImport } from './routes/$owner/$repo/$'
import { Route as ApiRawOwnerRepoShaSplatRouteImport } from './routes/api/raw/$owner/$repo/$sha/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev/preview',
  path: '/dev/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubInstallRoute = GithubInstallRouteImport.update({
  id: '/github/install',
  path: '/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubInstalledRoute = GithubInstalledRouteImport.update({
  id: '/github/installed',
  path: '/github/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoSplatRoute = OwnerRepoSplatRouteImport.update({
  id: '/$owner/$repo/$',
  path: '/$owner/$repo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawOwnerRepoShaSplatRoute = ApiRawOwnerRepoShaSplatRouteImport.update({
  id: '/api/raw/$owner/$repo/$sha/$',
  path: '/api/raw/$owner/$repo/$sha/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dev/preview': typeof DevPreviewRoute
  '/github/install': typeof GithubInstallRoute
  '/github/installed': typeof GithubInstalledRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/api/raw/$owner/$repo/$sha/$': typeof ApiRawOwnerRepoShaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dev/preview': typeof DevPreviewRoute
  '/github/install': typeof GithubInstallRoute
  '/github/installed': typeof GithubInstalledRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/api/raw/$owner/$repo/$sha/$': typeof ApiRawOwnerRepoShaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dev/preview': typeof DevPreviewRoute
  '/github/install': typeof GithubInstallRoute
  '/github/installed': typeof GithubInstalledRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/api/raw/$owner/$repo/$sha/$': typeof ApiRawOwnerRepoShaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dev/preview'
    | '/github/install'
    | '/github/installed'
    | '/$owner/$repo/$'
    | '/api/raw/$owner/$repo/$sha/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dev/preview'
    | '/github/install'
    | '/github/installed'
    | '/$owner/$repo/$'
    | '/api/raw/$owner/$repo/$sha/$'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dev/preview'
    | '/github/install'
    | '/github/installed'
    | '/$owner/$repo/$'
    | '/api/raw/$owner/$repo/$sha/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  DevPreviewRoute: typeof DevPreviewRoute
  GithubInstallRoute: typeof GithubInstallRoute
  GithubInstalledRoute: typeof GithubInstalledRoute
  OwnerRepoSplatRoute: typeof OwnerRepoSplatRoute
  ApiRawOwnerRepoShaSplatRoute: typeof ApiRawOwnerRepoShaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/preview': {
      id: '/dev/preview'
      path: '/dev/preview'
      fullPath: '/dev/preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/install': {
      id: '/github/install'
      path: '/github/install'
      fullPath: '/github/install'
      preLoaderRoute: typeof GithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/installed': {
      id: '/github/installed'
      path: '/github/installed'
      fullPath: '/github/installed'
      preLoaderRoute: typeof GithubInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$': {
      id: '/$owner/$repo/$'
      path: '/$owner/$repo/$'
      fullPath: '/$owner/$repo/$'
      preLoaderRoute: typeof OwnerRepoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw/$owner/$repo/$sha/$': {
      id: '/api/raw/$owner/$repo/$sha/$'
      path: '/api/raw/$owner/$repo/$sha/$'
      fullPath: '/api/raw/$owner/$repo/$sha/$'
      preLoaderRoute: typeof ApiRawOwnerRepoShaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  DevPreviewRoute: DevPreviewRoute,
  GithubInstallRoute: GithubInstallRoute,
  GithubInstalledRoute: GithubInstalledRoute,
  OwnerRepoSplatRoute: OwnerRepoSplatRoute,
  ApiRawOwnerRepoShaSplatRoute: ApiRawOwnerRepoShaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
